import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding 2025 Shanghai Yueqing Chamber members...');

  const members = [
    {
      name: "高天乐",
      phone: "15801788878",
      company: "浙江天正电气股份有限公司",
      position: "董事长",
      district: "浦东",
      chamberTitle: "会长",
    },
    {
      name: "石向才",
      phone: "13867776666",
      company: "电光防爆科技股份有限公司",
      position: "董事局主席",
      district: "闵行",
      chamberTitle: "监事长",
    },
    {
      name: "胡成国",
      phone: "13800000000",
      company: "上海德力西集团有限公司",
      position: "董事长",
      district: "",
      chamberTitle: "执行会长2025",
    },
    {
      name: "王吉雷",
      phone: "13901858888",
      company: "中通快递股份有限公司",
      position: "董事、联合创始人",
      district: "青浦",
      chamberTitle: "执行会长",
    },
    {
      name: "胡志荣",
      phone: "13671555555",
      company: "华荣科技股份有限公司",
      position: "董事长",
      district: "嘉定",
      chamberTitle: "执行会长",
    },
    {
      name: "石华辉",
      phone: "13957189888",
      company: "上海创力集团股份有限公司",
      position: "董事长",
      district: "青浦",
      chamberTitle: "执行会长",
    },
    {
      name: "包秀银",
      phone: "13601866666",
      company: "南亚新材料科技股份有限公司",
      position: "董事长",
      district: "嘉定",
      chamberTitle: "执行会长",
    },
    {
      name: "陈余义",
      phone: "13918965777",
      company: "上海浦东电线电缆（集团）有限公司",
      position: "董事长",
      district: "奉贤",
      chamberTitle: "执行会长",
    },
    {
      name: "李振林",
      phone: "13901666896",
      company: "上海金开利集团",
      position: "副董事长",
      district: "黄浦",
      chamberTitle: "执行会长",
    },
    {
      name: "陈汉星",
      phone: "13917911111",
      company: "上海隆众产业园",
      position: "主任",
      district: "杨浦",
      chamberTitle: "执行会长",
    },
    {
      name: "郑立克",
      phone: "13901878052",
      company: "爱康企业集团（上海）有限公司",
      position: "董事长",
      district: "浦东",
      chamberTitle: "执行会长",
    },
    {
      name: "胡晨阳",
      phone: "13386093619",
      company: "北京市京师（上海）律师事务所",
      position: "主任",
      district: "静安",
      chamberTitle: "执行会长",
    },
    {
      name: "张瑞根",
      phone: "18930226666",
      company: "泽大（上海）律师事务所",
      position: "执行主任",
      district: "静安",
      chamberTitle: "执行会长",
    },
    {
      name: "黄岁飞",
      phone: "13506678988",
      company: "上海晶茂投资有限公司",
      position: "董事长",
      district: "奉贤",
      chamberTitle: "执行会长",
    },
    {
      name: "施甘云",
      phone: "13601721198",
      company: "上海申之江珠宝集团有限公司",
      position: "董事长",
      district: "黄浦",
      chamberTitle: "执行会长",
    },
    {
      name: "包燕微",
      phone: "13968711888",
      company: "上海歌特维生物科技集团",
      position: "董事长",
      district: "浦东",
      chamberTitle: "执行会长",
    },
    {
      name: "李玲珠",
      phone: "13701857222",
      company: "上海乐港电器有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "执行会长",
    },
    {
      name: "毛海渊",
      phone: "13906933355",
      company: "摩融控股集团有限公司",
      position: "董事长",
      district: "青浦",
      chamberTitle: "执行会长",
    },
    {
      name: "陈品旺",
      phone: "13905879111",
      company: "上海菲姿服饰有限公司",
      position: "董事长",
      district: "松江",
      chamberTitle: "执行会长",
    },
    {
      name: "谢斌",
      phone: "13331999077",
      company: "上海宝临防爆电器有限公司",
      position: "董事长",
      district: "宝山",
      chamberTitle: "执行会长",
    },
    {
      name: "吴中平",
      phone: "13901643415",
      company: "中色国际控股集团有限公司",
      position: "董事长",
      district: "静安",
      chamberTitle: "执行会长",
    },
    {
      name: "张国余",
      phone: "13311819155",
      company: "大宅金瑞商业管理有限公司",
      position: "董事长",
      district: "嘉定",
      chamberTitle: "常务副会长",
    },
    {
      name: "倪建生",
      phone: "13916011788",
      company: "上海索谷电缆集团有限公司",
      position: "董事长",
      district: "奉贤",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈叔明",
      phone: "13916805999",
      company: "上海胜华电气股份有限公司",
      position: "董事长",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈磊",
      phone: "13901691085",
      company: "上海中科电气（集团）有限公司",
      position: "总裁",
      district: "虹口",
      chamberTitle: "常务副会长",
    },
    {
      name: "郑建松",
      phone: "13817785555",
      company: "上海千洲实业有限公司",
      position: "董事长",
      district: "嘉定",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈旭鹏",
      phone: "18930588888",
      company: "上海穆勒四通电气股份有限公司",
      position: "董事长",
      district: "金山",
      chamberTitle: "常务副会长",
    },
    {
      name: "余建东",
      phone: "13501717581",
      company: "上海循道新能源科技有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "胡建新",
      phone: "13585823588",
      company: "上海新龙塑料制造有限公司",
      position: "董事长",
      district: "闵行",
      chamberTitle: "常务副会长",
    },
    {
      name: "赵安奶",
      phone: "13816365988",
      company: "上海安南正泰集团电器有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "王陈松",
      phone: "13817782222",
      company: "上海丹泉泵业（集团）有限公司",
      position: "董事长",
      district: "奉贤",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈小玲",
      phone: "15900975777",
      company: "上海朗浩控股有限公司",
      position: "董事长",
      district: "长宁",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈余雷",
      phone: "13918101555",
      company: "上海胜华特种电缆有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "杨从新",
      phone: "13761971111",
      company: "上海金钟电气集团",
      position: "董事长",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈智",
      phone: "13774495556",
      company: "上海永进电缆（集团）有限公司",
      position: "总裁",
      district: "奉贤",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈琼",
      phone: "13917277777",
      company: "上海正泰电器销售有限公司",
      position: "总经理",
      district: "嘉定",
      chamberTitle: "常务副会长",
    },
    {
      name: "吴方忠　",
      phone: "13868788666",
      company: "上海侨亨实业有限公司",
      position: "董事长",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "郑利锴",
      phone: "13901995268",
      company: "上海龙泓国际贸易有限公司",
      position: "总经理",
      district: "虹口",
      chamberTitle: "常务副会长",
    },
    {
      name: "张春媚",
      phone: "13816806099",
      company: "上海宝鹿车业有限公司",
      position: "董事长",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "郑定丰",
      phone: "13817688828",
      company: "上海仑科电气集团有限公司",
      position: "总经理",
      district: "静安",
      chamberTitle: "常务副会长",
    },
    {
      name: "薛文峰",
      phone: "13757778333",
      company: "上海长江电气设备集团有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "施瑶杰",
      phone: "13818607888",
      company: "上海北变科技股份有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "郑温乐",
      phone: "13817383269",
      company: "上海港程投资咨询有限公司",
      position: "董事长",
      district: "虹口",
      chamberTitle: "常务副会长",
    },
    {
      name: "吴青燕",
      phone: "13706773362",
      company: "美丰农业科技（上海）有限公司",
      position: "副总经理",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "张相矛",
      phone: "13777733232",
      company: "上海皋金实业有限公司",
      position: "董事长",
      district: "徐汇",
      chamberTitle: "常务副会长",
    },
    {
      name: "郑奔",
      phone: "13968733870",
      company: "上海胜华电缆科技集团有限公司",
      position: "营销总经理",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "施金标",
      phone: "13501961999",
      company: "上海申旗投资有限公司、上海国延堂医药科技有限公司",
      position: "总裁",
      district: "黄埔",
      chamberTitle: "常务副会长",
    },
    {
      name: "黄云斌",
      phone: "13818887077",
      company: "上海精科智能科技股份有限公司",
      position: "董事长",
      district: "松江",
      chamberTitle: "常务副会长2025",
    },
    {
      name: "张丽园",
      phone: "13661792777",
      company: "上海同燕堂生物科技有限责任公司",
      position: "总经理",
      district: "闵行",
      chamberTitle: "常务副会长2025",
    },
    {
      name: "施银节",
      phone: "13601735600",
      company: "上海建桥集团",
      position: "副董事长",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "李丰林",
      phone: "13918607888",
      company: "上海浦东电线电缆（集团）有限公司",
      position: "总裁",
      district: "奉贤",
      chamberTitle: "常务副会长",
    },
    {
      name: "王爱华",
      phone: "13858069168",
      company: "浙江创力融资租赁有限公司",
      position: "常务副总",
      district: "青浦",
      chamberTitle: "常务副会长",
    },
    {
      name: "臧微萍",
      phone: "13806607769",
      company: "上海菲姿服饰有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "方立坚",
      phone: "13601055011",
      company: "中通云商供应链有限公司",
      position: "总经理",
      district: "青浦",
      chamberTitle: "常务副会长",
    },
    {
      name: "施鹏",
      phone: "13817377777",
      company: "电光防爆科技（上海）有限公司",
      position: "总经理",
      district: "闵行",
      chamberTitle: "常务副会长",
    },
    {
      name: "赵建红",
      phone: "18930877055",
      company: "上海隆众原生物科技有限公司 ",
      position: "总经理",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "胡慧娟",
      phone: "13800000000",
      company: "",
      position: "",
      district: "",
      chamberTitle: "",
    },
    {
      name: "包天培",
      phone: "15821772801",
      company: "爱康企业集团（上海）有限公司",
      position: "副总",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "陈勇",
      phone: "13901871831",
      company: "上海贝特医疗器械有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "金爱武",
      phone: "13901967815",
      company: "中期贵金属电子商务（上海）有限公司",
      position: "董事长",
      district: "黄浦",
      chamberTitle: "常务副会长",
    },
    {
      name: "胡星友",
      phone: "13651788788",
      company: "上海久电电力集团有限公司",
      position: "董事长",
      district: "杨浦",
      chamberTitle: "理事",
    },
    {
      name: "黄兴良",
      phone: "13917116658",
      company: "上海金诚建设发展有限公司",
      position: "董事长",
      district: "嘉定",
      chamberTitle: "理事",
    },
    {
      name: "陈天荣",
      phone: "13917855188",
      company: "上海美上置业开发有限公司",
      position: "董事长",
      district: "杨浦",
      chamberTitle: "理事",
    },
    {
      name: "黄紫诺",
      phone: "13817856929",
      company: "上海昶鑫诚建筑工程有限公司",
      position: "总经理",
      district: "静安",
      chamberTitle: "理事",
    },
    {
      name: "陈建宝",
      phone: "13816918888",
      company: "上海格林德斯木业有限公司",
      position: "董事长",
      district: "嘉定",
      chamberTitle: "理事",
    },
    {
      name: "叶理克",
      phone: "13905873901",
      company: "长城电器集团上海有限公司",
      position: "总经理",
      district: "金山",
      chamberTitle: "理事",
    },
    {
      name: "钱匡",
      phone: "13601917188",
      company: "上海金电铜业有限公司",
      position: "总经理",
      district: "静安",
      chamberTitle: "理事",
    },
    {
      name: "叶海萍",
      phone: "13968716862",
      company: "上海豪进钢铁贸易有限公司",
      position: "董事长",
      district: "静安",
      chamberTitle: "理事",
    },
    {
      name: "李祥武",
      phone: "13817188588",
      company: "上海鑫中兴防爆科技有限公司",
      position: "总经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "余节仁",
      phone: "13701759861",
      company: "上海天银电器有限公司",
      position: "总经理",
      district: "静安",
      chamberTitle: "理事",
    },
    {
      name: "郑佑俊",
      phone: "13817609111",
      company: "上海德宝密封件有限公司",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事",
    },
    {
      name: "林升河",
      phone: "15900500789",
      company: "上海盛鑫糖酒食品有限公司",
      position: "总经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "金飞",
      phone: "13780102880",
      company: "上海嘉红食品有限公司",
      position: "总经理",
      district: "嘉定",
      chamberTitle: "理事",
    },
    {
      name: "黄冬冬",
      phone: "13774202020",
      company: "上海丰泰实业发展有限公司",
      position: "董事长",
      district: "嘉定",
      chamberTitle: "理事",
    },
    {
      name: "张辉",
      phone: "13917870623",
      company: "上海怀惠实业有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "周安峰",
      phone: "13901747892",
      company: "上海贺新投资咨询有限公司",
      position: "总经理",
      district: "徐汇",
      chamberTitle: "理事",
    },
    {
      name: "胡小红",
      phone: "13901922103",
      company: "上海五林电控设备有限公司",
      position: "经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "林妙丽",
      phone: "13916532151",
      company: "上海基燕机电有限公司",
      position: "总财务经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "黄伟",
      phone: "15900431111",
      company: "中变集团上海变压器有限公司",
      position: "总经理",
      district: "金山",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈秀银",
      phone: "13918187852",
      company: "上海美岛电气配套有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "黄旭印",
      phone: "13601727818",
      company: "上海欣咏电子有限公司",
      position: "总经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "吴方亮",
      phone: "13681615982",
      company: "上海乐成电子科技有限公司",
      position: "总经理",
      district: "静安",
      chamberTitle: "理事",
    },
    {
      name: "杨志勇",
      phone: "13901749869",
      company: "上海耐力电控设备有限公司",
      position: "董事/副总经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "南存龙",
      phone: "13761827777",
      company: "上海瓯亚机电设备有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "朱立存",
      phone: "18841475266",
      company: "上海人民电器开关厂有限公司  ",
      position: "销售经理",
      district: "徐汇",
      chamberTitle: "理事",
    },
    {
      name: "陈云勇",
      phone: "13916331777",
      company: "上海复大品牌研究所有限公司",
      position: "所长",
      district: "徐汇",
      chamberTitle: "理事",
    },
    {
      name: "叶理获",
      phone: "13291731073",
      company: "上海翰煜管理咨询中心（有限合伙）",
      position: "董事长",
      district: "",
      chamberTitle: "理事",
    },
    {
      name: "张雁红",
      phone: "13956183787",
      company: "上海中岛广源企业咨询有限公司",
      position: "董事长",
      district: "闵行",
      chamberTitle: "理事",
    },
    {
      name: "郑祥英",
      phone: "1376128777",
      company: "上海侨亨实业有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "理事",
    },
    {
      name: "倪晓敏",
      phone: "13506672520",
      company: "浙江敏乐船舶科技有限公司",
      position: "总经理",
      district: "",
      chamberTitle: "理事",
    },
    {
      name: "李孙龙",
      phone: "13761685555",
      company: "上海晟江机械设备有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "郑荷芬",
      phone: "13585567866",
      company: "上海新龙塑料制造有限公司",
      position: "财务总监",
      district: "闵行",
      chamberTitle: "理事",
    },
    {
      name: "赵顺荣",
      phone: "13905871859",
      company: "上海卓帅汽车技术有限公司 ",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "朱清林",
      phone: "13916790999",
      company: "上海众业通电缆股份有限公司",
      position: "董事长",
      district: "奉贤",
      chamberTitle: "理事",
    },
    {
      name: "万丁海",
      phone: "13585766186",
      company: "上海分镜文化传媒有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "徐克盛",
      phone: "13671503555",
      company: "上海伊顿通用设备有限公司 ",
      position: "总经理",
      district: "奉贤",
      chamberTitle: "理事",
    },
    {
      name: "高建德",
      phone: "18221999996",
      company: "上海鑫颖金属材料有限公司",
      position: "总经理",
      district: "奉贤",
      chamberTitle: "理事",
    },
    {
      name: "南存赞",
      phone: "13764301432",
      company: "上海永瑞流体技术有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "理事",
    },
    {
      name: "南朋双",
      phone: "13801800897",
      company: "南喆电气科技（上海）有限公司",
      position: "总经理",
      district: "金山",
      chamberTitle: "理事",
    },
    {
      name: "南君泉",
      phone: "13917386616",
      company: "上海固安祥电气配套有限公司",
      position: "总经理",
      district: "普陀",
      chamberTitle: "理事",
    },
    {
      name: "李特",
      phone: "18018658666",
      company: "上海启世投资管理有限公司",
      position: "总经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "包希明",
      phone: "13901871820",
      company: "上海基艳机电有限公司",
      position: "总经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "陈泽",
      phone: "13524339774",
      company: "上海来石文化创意设计有限公司",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事",
    },
    {
      name: "陈振刚",
      phone: "13761273979",
      company: "上海通用重工集团有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "李乐超",
      phone: "18917742322",
      company: "上海申开电力建设工程有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "朱小春",
      phone: "13868718587",
      company: "悦儿国际贸易（上海）有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "张珍妃",
      phone: "13003115412",
      company: "上海电器厂实业有限公司",
      position: "经理",
      district: "虹口",
      chamberTitle: "理事",
    },
    {
      name: "陈永杰",
      phone: "13777733377",
      company: "上海永源企业发展股份有限公司",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事",
    },
    {
      name: "林道善",
      phone: "13916291888",
      company: "上海涵博生物科技有限公司",
      position: "总经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "金声扬",
      phone: "13818185777",
      company: "上海市少年儿童业余美术学校",
      position: "理事长",
      district: "黄浦",
      chamberTitle: "理事",
    },
    {
      name: "施乐翔",
      phone: "18916069799",
      company: "平安银行股份有限公司上海外滩支行",
      position: "副行长",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "徐财源",
      phone: "13918603567",
      company: "财源在线（上海）网络科技有限公司",
      position: "董事长",
      district: "浦东",
      chamberTitle: "理事2021",
    },
    {
      name: "余旭雷",
      phone: "13901831469",
      company: "上海户泰五金机电有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "理事2021",
    },
    {
      name: "叶树民",
      phone: "18901875555",
      company: "上海雅易电气有限公司",
      position: "总经理",
      district: "奉贤",
      chamberTitle: "理事2021",
    },
    {
      name: "金胜威",
      phone: "13816127858",
      company: "上海硕玛电气有限公司",
      position: "总经理",
      district: "青浦",
      chamberTitle: "理事2021",
    },
    {
      name: "金林辉",
      phone: "13310160518",
      company: "上海盛临贸易有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事2021",
    },
    {
      name: "庄庆冠",
      phone: "13757758777",
      company: "上海海之仙餐饮管理有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事2021",
    },
    {
      name: "张湖克",
      phone: "13371958058",
      company: "上海宝临照明科技股份有限公司",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事2021",
    },
    {
      name: "吴旭东",
      phone: "13310160511",
      company: "上海盛佰贸易有限公司",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事2021",
    },
    {
      name: "钱旭敏",
      phone: "18101611001",
      company: "上海文歌电气有限公司",
      position: "总经理",
      district: "静安",
      chamberTitle: "理事2021",
    },
    {
      name: "戴国清",
      phone: "13701792212",
      company: "上海节高电子科技有限公司",
      position: "总经理",
      district: "闵行",
      chamberTitle: "理事2021",
    },
    {
      name: "李登",
      phone: "13818179555",
      company: "光大证券股份有限公司",
      position: "投资顾问",
      district: "浦东",
      chamberTitle: "理事2021",
    },
    {
      name: "胡洪丽",
      phone: "13818505777",
      company: "夜光杯酒业",
      position: "合伙人",
      district: "普陀区",
      chamberTitle: "理事2021",
    },
    {
      name: "陈浩放",
      phone: "13817435666",
      company: "德标管业（上海）有限公司",
      position: "采购",
      district: "奉贤",
      chamberTitle: "理事2021",
    },
    {
      name: "陈也丹",
      phone: "13611610775",
      company: "上海圆正财务咨询有限公司",
      position: "机构负责人",
      district: "宝山",
      chamberTitle: "理事2021",
    },
    {
      name: "陈文旺",
      phone: "17302118989",
      company: "上海伟肯实业有限公司",
      position: "副总经理",
      district: "嘉定区",
      chamberTitle: "理事2022",
    },
    {
      name: "魏少强",
      phone: "17701768138",
      company: "上海浦广科技（集团）有限公司",
      position: "销售副总",
      district: "嘉定区",
      chamberTitle: "理事2022",
    },
    {
      name: "叶柏盛",
      phone: "13651983222",
      company: "上海柏威流体控制技术有限公司",
      position: "总经理",
      district: "金山",
      chamberTitle: "理事2022",
    },
    {
      name: "郑立威",
      phone: "13761610571",
      company: "上海嘉强典当有限公司",
      position: "总经理",
      district: "徐汇区",
      chamberTitle: "理事",
    },
    {
      name: "倪浩",
      phone: "15618501788",
      company: "海通证券股份有限公司",
      position: "企业金融部",
      district: "",
      chamberTitle: "理事",
    },
    {
      name: "范长河",
      phone: "13868785151",
      company: "温州银行上海分行松江业务部",
      position: "总经理",
      district: "",
      chamberTitle: "理事",
    },
    {
      name: "王梦非",
      phone: "18858787000",
      company: "浙江乐粉轨道交通科技有限公司",
      position: "总经理",
      district: "",
      chamberTitle: "理事",
    },
    {
      name: "郑志强",
      phone: "13482066111",
      company: "上海浙商典当有限公司",
      position: "总经理",
      district: "",
      chamberTitle: "理事",
    },
    {
      name: "金早洁",
      phone: "13506557713",
      company: "上海柯正资产管理有限公司",
      position: "风控总监",
      district: "浦东",
      chamberTitle: "理事2021",
    },
    {
      name: "戴秀燕",
      phone: "18701717028",
      company: "紫宸峰（上海）贸易有限公司",
      position: "总经理",
      district: "青浦",
      chamberTitle: "理事2024",
    },
    {
      name: "王春竹",
      phone: "13800000000",
      company: "上海于上机电设备有限公司",
      position: "销售经理",
      district: "",
      chamberTitle: "理事2024",
    },
    {
      name: "郑展",
      phone: "13524885636",
      company: "华泰证券股份有限公司",
      position: "高级经理",
      district: "",
      chamberTitle: "F",
    },
    {
      name: "章全琪",
      phone: "13524010345",
      company: "电管家集团股份有限公司",
      position: "合伙人",
      district: "",
      chamberTitle: "理事2024",
    },
    {
      name: "陈海燕",
      phone: "13800000000",
      company: "乐清农商银行",
      position: "",
      district: "",
      chamberTitle: "理事2024",
    },
    {
      name: "陈明辉",
      phone: "15869635445",
      company: "浙商银行上海分行",
      position: "",
      district: "静安",
      chamberTitle: "理事2024",
    },
    {
      name: "姚章帆",
      phone: "13817458597",
      company: "上海婴珂商贸有限公司",
      position: "电商运营经理",
      district: "静安",
      chamberTitle: "理事2024",
    },
    {
      name: "陈权",
      phone: "13818774555",
      company: " 上海西源宏电气设备有限公司 ",
      position: "副总",
      district: "浦东",
      chamberTitle: "理事2024",
    },
    {
      name: "郑碎萍",
      phone: "13918182678",
      company: "上海华容防爆科技有限公司",
      position: "销售经理",
      district: "静安",
      chamberTitle: "理事2024",
    },
    {
      name: "高翔",
      phone: "15821270571",
      company: "上海联华变压器厂有限公司",
      position: "总经理",
      district: "奉贤",
      chamberTitle: "理事2021",
    },
    {
      name: "李维中",
      phone: "13321996579",
      company: "上海日晋工程塑料有限公司",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事2024",
    },
    {
      name: "钱凌志",
      phone: "13310101107",
      company: "上海野马浜律师事务所",
      position: "权益合伙人",
      district: "黄埔区",
      chamberTitle: "理事2025",
    },
    {
      name: "唐泽轩",
      phone: "15067701863",
      company: "上海新缆电缆有限公司",
      position: "经理",
      district: "奉贤区",
      chamberTitle: "理事2025",
    },
    {
      name: "刘茂灼",
      phone: "15316808552",
      company: "上海浦东软件园汇智科技有限公司",
      position: "会员",
      district: "浦东",
      chamberTitle: "理事2025",
    },
    {
      name: "陈小兵",
      phone: "13761891891",
      company: "上海胜华电气股份有限公司",
      position: "副总裁",
      district: "浦东",
      chamberTitle: "理事2025",
    },
    {
      name: "郑丽丹",
      phone: "18962831777",
      company: "上海嘉盟电力设备有限公司",
      position: "行政总监",
      district: "金山",
      chamberTitle: "理事2025",
    },
    {
      name: "柯林伟",
      phone: "18368787887",
      company: "上海鸿幸盛实业有限公司",
      position: "总经理",
      district: "松江区",
      chamberTitle: "理事2025",
    },
    {
      name: "王永超",
      phone: "13916913666",
      company: "上海东方刺绣家纺有限公司",
      position: "总经理",
      district: "松江区",
      chamberTitle: "理事2025",
    },
    {
      name: "洪伽沁",
      phone: "13800000000",
      company: "上海希富实业发展有限公司",
      position: "",
      district: "",
      chamberTitle: "理事2026",
    },
    {
      name: "高奇驰",
      phone: "13671715115",
      company: "上海奇皮尔电气制造有限公司 ",
      position: "",
      district: "",
      chamberTitle: "理事2026",
    },
    {
      name: "刘志高",
      phone: "15021777713",
      company: "上海一康康复医院股份有限公司",
      position: "董事长",
      district: "徐汇",
      chamberTitle: "执行会长",
    },
    {
      name: "钱金成",
      phone: "13162245678",
      company: "德汇融资租赁有限公司",
      position: "副董事长兼总经理",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "朱乐千",
      phone: "13905873007",
      company: "上海瑞奇汽配有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "理事",
    },
    {
      name: "陈磊",
      phone: "18621011580",
      company: "上海金蓝机电设备成套有限公司",
      position: "经理",
      district: "嘉定",
      chamberTitle: "理事",
    },
    {
      name: "郑彩乐",
      phone: "13918226666",
      company: "上海欧士通机电设备有限公司",
      position: "总经理",
      district: "奉贤",
      chamberTitle: "理事",
    },
    {
      name: "徐粟",
      phone: "15000610503",
      company: "东禾健康管理（上海）有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "王一一",
      phone: "13800000000",
      company: "",
      position: "",
      district: "",
      chamberTitle: "",
    },
    {
      name: "徐传勇",
      phone: "13800000000",
      company: "",
      position: "",
      district: "",
      chamberTitle: "",
    },
    {
      name: "王思龙",
      phone: "13800000000",
      company: "",
      position: "",
      district: "",
      chamberTitle: "",
    },
    {
      name: "陈琢",
      phone: "13671710281",
      company: "上海易维堡信息科技有限公司",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事2021",
    },
    {
      name: "杨玉晓",
      phone: "13661758833",
      company: "上海展元国际贸易有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事2021",
    },
    {
      name: "张小兰",
      phone: "13505876526",
      company: "古墨风韵（杭州）影视文化传媒有限责任公司",
      position: "副总经理",
      district: "黄埔",
      chamberTitle: "理事",
    },
    {
      name: "郑元虎",
      phone: "13916551457",
      company: "上海和田光电技术有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "陈文葆",
      phone: "13905872746",
      company: "合兴集团有限公司",
      position: "董事长",
      district: "松江",
      chamberTitle: "执行会长",
    },
    {
      name: "林忠福",
      phone: "13916566477",
      company: "上海中塑管业有限公司",
      position: "副总经理",
      district: "金山",
      chamberTitle: "理事",
    },
    {
      name: "郑祥义",
      phone: "13816578666",
      company: "上海中塑管业有限公司",
      position: "总经理",
      district: "金山",
      chamberTitle: "理事",
    },
    {
      name: "钱金耐",
      phone: "13818068688",
      company: "德汇实业集团有限公司",
      position: "董事长",
      district: "浦东",
      chamberTitle: "执行会长",
    },
    {
      name: "余晓泉",
      phone: "13917866788",
      company: "德汇实业集团有限公司",
      position: "部长",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "陈升旦",
      phone: "13601853888",
      company: "上海信统电器有限公司",
      position: "董事长",
      district: "黄埔",
      chamberTitle: "常务副会长",
    },
    {
      name: "徐顺宝",
      phone: "13801712131",
      company: "上海南自科技股份有限公司",
      position: "董事长",
      district: "普陀",
      chamberTitle: "常务副会长",
    },
    {
      name: "屠方记",
      phone: "15316885889",
      company: "上海宏挺机械设备制造有限公司 上海宏挺紧固件制造有限公司",
      position: "董事长",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "赵建新",
      phone: "13701735601",
      company: "上海埃科燃气测控设备有限公司",
      position: "总经理",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "南程成",
      phone: "13310118828",
      company: "上海俏达健康管理有限公司",
      position: "ceo",
      district: "闵行",
      chamberTitle: "常务副会长",
    },
    {
      name: "付献宇",
      phone: "13321865558",
      company: "上海柯付林实业有限公司",
      position: "总经理",
      district: "嘉定",
      chamberTitle: "理事",
    },
    {
      name: "孙攀",
      phone: "13816890617",
      company: "上海精珅新材料有限公司",
      position: "总经理",
      district: "金山",
      chamberTitle: "理",
    },
    {
      name: "朱卓敏",
      phone: "18621570606",
      company: "上海电享信息科技有限公司",
      position: "创始人/ceo",
      district: "普陀",
      chamberTitle: "常务副会长",
    },
    {
      name: "王国良",
      phone: "13641847777",
      company: "上海友邦电气（集团）股份有限公司",
      position: "董事长",
      district: "松江",
      chamberTitle: "常务副会长",
    },
    {
      name: "王培建",
      phone: "15921131111",
      company: "衡宝科技（上海）有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "吴旭雄",
      phone: "13601612345",
      company: "上海凯士邦企业发展有限公司",
      position: "董事长",
      district: "浦东",
      chamberTitle: "常务副会长",
    },
    {
      name: "周克",
      phone: "15000104554",
      company: "上海华一电气（集团）有限公司",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事",
    },
    {
      name: "高知克",
      phone: "13671540777",
      company: "上海飞策防爆电器有限公司",
      position: "总经理",
      district: "闸北",
      chamberTitle: "常务副会长",
    },
    {
      name: "吴杰",
      phone: "13788958185",
      company: "上海亲易实业集团有限公司",
      position: "执行总裁",
      district: "浦东",
      chamberTitle: "理事",
    },
    {
      name: "朱银海",
      phone: "15618159999",
      company: "上海胜华环保科技集团有限公司 ",
      position: "",
      district: "浦东",
      chamberTitle: "理事2021",
    },
    {
      name: "叶定强",
      phone: "18604352228",
      company: "安能允智慧（上海）能源有限公司",
      position: "总经理",
      district: "嘉定",
      chamberTitle: "理事2024",
    },
    {
      name: "叶选高",
      phone: "13905879268",
      company: "上海科常工程管理咨询中心",
      position: "总经理",
      district: "宝山",
      chamberTitle: "理事2021",
    },
    {
      name: "王建中",
      phone: "13818866229",
      company: "上海胜华电气股份有限公司",
      position: "副总裁",
      district: "浦东",
      chamberTitle: "理事2025",
    },
    {
      name: "虞娇蓉",
      phone: "13968710611",
      company: "上海德首实业有限公司",
      position: "总经理",
      district: "",
      chamberTitle: "理事",
    },
    {
      name: "金文义",
      phone: "13916769666",
      company: "上海浙南物流有限公司",
      position: "经理",
      district: "宝山",
      chamberTitle: "理事",
    },
    {
      name: "叶金欧",
      phone: "13681866626",
      company: "上海三开电气制造股份有限公司",
      position: "副总",
      district: "嘉定",
      chamberTitle: "理事",
    },
    {
      name: "石成海",
      phone: "13376276666",
      company: "上海郑民电器有限公司",
      position: "总经理",
      district: "",
      chamberTitle: "理事",
    },
    {
      name: "李乐微 ",
      phone: "13918593388",
      company: "深圳市瓯亚凯科技有限公司上海办事处",
      position: "主任",
      district: "杨浦",
      chamberTitle: "理事",
    },
    {
      name: "李剑",
      phone: "18721958288",
      company: "乐清市金春石斛有限公司",
      position: "总经理",
      district: "静安",
      chamberTitle: "理事",
    },
    {
      name: "郑春华",
      phone: "17863727288",
      company: "立帮秀珀化工涂料有限公司",
      position: "总经理",
      district: "浦东",
      chamberTitle: "理事2024",
    },
  ];

  for (const member of members) {
    await prisma.member.upsert({
      where: { phone: member.phone },
      update: {
        name: member.name,
        company: member.company,
        position: member.position,
        district: member.district,
        chamberTitle: member.chamberTitle,
      },
      create: member,
    });
  }

  console.log(`Seeded ${members.length} members.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });